apiVersion: apps/v1
kind: Deployment

metadata:
  name: admin-service
  namespace: dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: admin-service

  template:
    metadata:
      labels:
        app: admin-service

    spec:
      containers:
        - name: admin-service

          image: admin-service:v1

          imagePullPolicy: Never

          ports:
            - containerPort: 9007

          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-service.database.svc.cluster.local:5432/postgres

            - name: SPRING_DATASOURCE_USERNAME
              value: postgres

            - name: SPRING_DATASOURCE_PASSWORD
              value: "2001"